Homes page
IldarKamalov/airbnb-demo-frontend pull request #2
Opened 2018-01-10 21:13 UTC by IldarKamalov

2018-01-11 07:49 UTC, IldarKamalov commented
https://build-yvgafsampa.now.sh/

2018-01-11 19:26 UTC, evgenyrodionov commented
А где Apply / Cancel?

![image](https://user-images.githubusercontent.com/775692/34843036-6b90a88e-f71e-11e7-9c2d-bbb22bb4e26e.png)

2018-01-11 19:31 UTC, imevro requested changes

2018-01-11 19:31 UTC, evgenyrodionov commented on src/Homes/Filters/index.js
> +          <FiltersButton type="button" hiddenMobile>
ты и так в фильтерс, нах тебе префикс фильтр?

2018-01-11 19:31 UTC, evgenyrodionov commented on src/Homes/Pagination/index.js
> +            <Number to="/homes" current="true">1</Number>
а зачем ты передаешь булеан как строку?

надо `current={true}`, у реакта в пропах в `{}` выполняется джс

2018-01-11 19:31 UTC, evgenyrodionov commented on src/Homes/ShowMap/index.js
> +    return <Location />;
читай частые ошибки предыдущего этапа

2018-01-11 19:31 UTC, evgenyrodionov commented on src/Homes/index.js
> +                reviewsCount="221"
передавай числом

2018-01-11 19:31 UTC, evgenyrodionov commented on src/Landing/Experiences/Card.js
> +  <Card to={props.href}>
to={href}? где консистентность?

2018-01-11 19:31 UTC, evgenyrodionov commented on src/Landing/Explore/Category.js
> +export const Wrap = styled.div`
нах тебе враппер этот?

2018-01-12 08:33 UTC, IldarKamalov commented
https://build-bybiatycel.now.sh/homes

2018-01-12 13:46 UTC, imevro requested changes

2018-01-12 13:46 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +import { Filter } from './styled.js';
а зачем .джс?

2018-01-12 13:46 UTC, evgenyrodionov commented on src/Homes/Pagination/index.js
> +          <Number to="/homes">3</Number>
Number это тип данных в джсе!

2018-01-13 08:27 UTC, IldarKamalov commented
https://build-eiahrlculg.now.sh/

2018-01-13 08:51 UTC, evgenyrodionov commented
Календарь не работает — не могу выбрать значения в нём

2018-01-13 08:52 UTC, imevro requested changes

2018-01-13 08:52 UTC, evgenyrodionov commented on src/Homes/Filters/Dates/index.js
> +          <Filter onClick={this.toggleOpen} isOpen={this.state.isOpen}>
фильтр что?

2018-01-13 19:08 UTC, IldarKamalov commented
https://build-ahazixxlwj.now.sh/

2018-01-21 08:17 UTC, imevro requested changes

2018-01-21 08:17 UTC, evgenyrodionov commented on src/App.js
> +        <div className="App">
зачем ты держишь этот .App?

2018-01-21 08:17 UTC, evgenyrodionov commented on src/App.js
> +          <Route path="/" exact component={Footer} />
что мешает на лэндинге прописать, зачем роутом делать?

2018-01-21 08:17 UTC, evgenyrodionov commented on src/Footer/index.js
> +              <ListLink to="/">Careers</ListLink>
у тебя есть какой-то другой занятый Link, что тебе пришлось добавлять префикс List?

2018-01-21 08:17 UTC, evgenyrodionov commented on src/Homes/Filters/Dates/index.js
> +import './react_dates_overrides.css';
назови нормально

2018-01-21 08:17 UTC, evgenyrodionov commented on src/Homes/Info.js
> +    <div>
зачем этот див?

2018-01-21 19:21 UTC, IldarKamalov commented
https://build-bsfxrtwrtc.now.sh/

2018-01-22 14:34 UTC, imevro requested changes

2018-01-22 14:34 UTC, evgenyrodionov commented on src/Homes/Filters/Dates/index.js
> +import './reactDates.css';
это же компонент

2018-01-22 19:00 UTC, imevro approved these changes

2018-01-22 19:00 UTC, merged